# Symbolic Solver Configuration
# Configuration file for logic inference engine

# Dataset configuration
dataset:
  name: "LogicalDeduction"  # Available options: ProntoQA, ProofWriter, FOLIO, LogicalDeduction

paths:
  input_file: "outputs/deepseek/LogicalDeduction/translation/translation_results.json"
  output_file: "outputs/deepseek/LogicalDeduction/symbolic_solver/results.json"
  backup_LLM_result_path: ""

solver:
  backup_strategy: "random"  # choices: ["random", "LLM"]

processing:
  cleanup_cache: true
